try {
    hello()
}
catch(error) {
    console.log(error)
}

try {
    anotherFuncion()
}
catch{
    console.log("Esto es un error")
}